### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xuyuji9000** [coderbunker/prometheus-playground#1]
- [x] Update Dockerfile, make update version easier.

- [ ] Notification to wechat group

- [x] Build the image dependency

- [ ] Notification with mailgun

- [ ] Different sites' notification can be assigned to different teams

- [ ] Understand more about configuration management(potentially Chef)
